# Generated by Django 4.0.6 on 2022-08-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataresolve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200, unique=True, verbose_name='نام سمت شغلی')),
            ],
            options={
                'verbose_name_plural': 'سمت\u200cهای شغلی',
            },
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت زیر مجموعه')),
                ('icon', models.FileField(blank=True, upload_to='subsidiary_icon', verbose_name='آیکون')),
                ('icon_gold', models.FileField(blank=True, upload_to='subsidiary_icon', verbose_name='آیکون طلایی')),
                ('main_page_image', models.ImageField(blank=True, upload_to='subsidiary_main_image')),
                ('main_page_description', models.TextField(blank=True, verbose_name='متن زیر مجموعه در صفحه\u200cی اصلی')),
            ],
            options={
                'verbose_name_plural': 'شرکت\u200cهای زیر مجموعه',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('email_address', models.EmailField(blank=True, max_length=200, verbose_name='آدرس ایمیل')),
                ('whats_app_link', models.URLField(blank=True, max_length=2000, verbose_name='لینک واتساپ')),
                ('inner_company_prefix_phone', models.IntegerField(blank=True, null=True, verbose_name='تلفن داخلی')),
                ('gender', models.CharField(choices=[('G', 'خانم'), ('B', 'آقا')], default='B', max_length=10, verbose_name='جنسیت')),
                ('image', models.ImageField(blank=True, upload_to='employees_data', verbose_name='عکس')),
                ('fields', models.ManyToManyField(blank=True, limit_choices_to={'category_type': 'main'}, related_name='job_fields', to='dataresolve.productcategories', verbose_name='فیلد\u200cهای تخصصی')),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_cat', to='company_data.jobcategories', verbose_name='سمت شغلی')),
            ],
            options={
                'verbose_name_plural': 'کارمندان',
            },
        ),
    ]
