# Generated by Django 4.0.6 on 2022-07-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataresolve', '0008_alter_productnames_product_sub_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'سمت\u200cهای شغلی',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(blank=True, max_length=200)),
                ('whats_app_link', models.URLField(blank=True, max_length=2000)),
                ('inner_company_prefix_phone', models.IntegerField(blank=True)),
                ('gender', models.CharField(default='B', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='employees_data', verbose_name='عکس')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_field', to='dataresolve.productnames', verbose_name='فیلد تخصصی')),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_cat', to='company_data.jobcategories', verbose_name='سمت شغلی')),
            ],
            options={
                'verbose_name_plural': 'کارمندان',
            },
        ),
    ]
