# Generated by Django 4.0.6 on 2022-07-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(blank=True, max_length=200, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='B', max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='inner_company_prefix_phone',
            field=models.IntegerField(blank=True, verbose_name='تلفن داخلی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='whats_app_link',
            field=models.URLField(blank=True, max_length=2000, verbose_name='لینک واتساپ'),
        ),
        migrations.AlterField(
            model_name='jobcategories',
            name='job_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام سمت شغلی'),
        ),
    ]
