# Generated by Django 4.0.6 on 2022-08-04 08:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=False, quality=100, scale=None, size=[120, None], upload_to='employees_data', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='main_page_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=False, quality=100, scale=None, size=[650, None], upload_to='subsidiary_main_image'),
        ),
    ]
