# Generated by Django 4.0.6 on 2022-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0002_alter_employee_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('G', 'خانم'), ('B', 'آقا')], default='B', max_length=10, verbose_name='جنسیت'),
        ),
    ]
