# Generated by Django 4.0.6 on 2022-07-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0008_alter_productnames_product_sub_name2'),
        ('company_data', '0003_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_field1', to='dataresolve.productcategories', verbose_name='فیلد تخصصی اول'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_category',
        ),
        migrations.AddField(
            model_name='employee',
            name='job_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='job_cat', to='company_data.jobcategories', verbose_name='سمت شغلی'),
        ),
    ]
