# Generated by Django 4.0.6 on 2022-07-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0008_alter_productnames_product_sub_name2'),
        ('company_data', '0004_alter_employee_field_remove_employee_job_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='field',
        ),
        migrations.AddField(
            model_name='employee',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='job_fields', to='dataresolve.productcategories', verbose_name='فیلد\u200cهای تخصصی'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_category',
        ),
        migrations.AddField(
            model_name='employee',
            name='job_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'main'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_cat', to='company_data.jobcategories', verbose_name='سمت شغلی'),
        ),
    ]
