# Generated by Django 4.0.6 on 2022-07-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0008_alter_productnames_product_sub_name2'),
        ('company_data', '0005_remove_employee_field_employee_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fields',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category_type': 'main'}, related_name='job_fields', to='dataresolve.productcategories', verbose_name='فیلد\u200cهای تخصصی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_cat', to='company_data.jobcategories', verbose_name='سمت شغلی'),
        ),
    ]
