# Generated by Django 4.0.6 on 2022-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0006_alter_employee_fields_alter_employee_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='inner_company_prefix_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='تلفن داخلی'),
        ),
    ]
