# Generated by Django 4.0.6 on 2022-07-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0007_alter_employee_inner_company_prefix_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت زیر مجموعه')),
                ('icon', models.FileField(blank=True, upload_to='subsidiary_icon', verbose_name='آیکون')),
                ('main_page_image', models.ImageField(blank=True, upload_to='subsidiary_main_image', verbose_name='عکس زیر\u200cمجموعه در صفحه\u200cی اصلی')),
                ('main_page_description', models.TextField(blank=True, verbose_name='متن زیر مجموعه در صفحه\u200cی اصلی')),
            ],
            options={
                'verbose_name_plural': 'شرکت\u200cهای زیر مجموعه',
            },
        ),
    ]
