# Generated by Django 4.0.6 on 2022-07-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0008_subsidiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='icon_gold',
            field=models.FileField(blank=True, upload_to='subsidiary_icon', verbose_name='آیکون طلایی'),
        ),
    ]
