# Generated by Django 4.0.6 on 2022-07-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0009_subsidiary_icon_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='main_page_image',
            field=models.ImageField(blank=True, upload_to='subsidiary_main_image'),
        ),
    ]
