# Generated by Django 4.0.6 on 2022-08-01 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleProductsAttributes',
            fields=[
                ('prod_value', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='مقدار صفت')),
            ],
            options={
                'verbose_name_plural': 'صفات کلی محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='نام ویژگی')),
                ('category_type', models.CharField(choices=[('main', 'اصلی'), ('alter', 'فرعی اول'), ('alter1', 'نام نمایش محصول')], default='اصلی', max_length=10, verbose_name='نوع ویژگی')),
            ],
            options={
                'verbose_name_plural': 'تمام انواع دسته\u200cبندی محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image_offer', models.ImageField(null=True, upload_to='offer_product_pic', verbose_name='عکس پشنهاد ویژه محصول')),
                ('att10_val', models.ManyToManyField(blank=True, related_name='att10_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن')),
                ('att1_val', models.ManyToManyField(blank=True, related_name='att1_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن')),
                ('att2_val', models.ManyToManyField(blank=True, related_name='att2_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن')),
                ('att3_val', models.ManyToManyField(blank=True, related_name='att3_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن')),
                ('att4_val', models.ManyToManyField(blank=True, related_name='att4_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن')),
                ('att5_val', models.ManyToManyField(blank=True, related_name='att5_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن')),
                ('att6_val', models.ManyToManyField(blank=True, related_name='att6_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن')),
                ('att7_val', models.ManyToManyField(blank=True, related_name='att7_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن')),
                ('att8_val', models.ManyToManyField(blank=True, related_name='att8_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن')),
                ('att9_val', models.ManyToManyField(blank=True, related_name='att9_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن')),
            ],
            options={
                'verbose_name_plural': 'تمام محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductNameStr',
            fields=[
                ('name', models.CharField(max_length=5000, primary_key=True, serialize=False)),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_name_str_name', to='dataresolve.productnames', verbose_name='نام محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsAttributes',
            fields=[
                ('attr_name', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True, verbose_name='نام صفت')),
            ],
            options={
                'verbose_name_plural': 'صفات محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductsPriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت')),
                ('last_price', models.FloatField(null=True, verbose_name='قیمت')),
                ('date_price_modified', models.DateTimeField(verbose_name='آخرین تغییر قیمت')),
                ('date_last_price_modified', models.DateTimeField(null=True, verbose_name='یکی قبل آخرین تغییر قیمت')),
                ('last_day_price', models.FloatField(null=True, verbose_name='قیمت روز قبل')),
                ('last_price_date', models.DateTimeField(null=True, verbose_name='آخرین قیمت پیشین')),
                ('hasOffer', models.BooleanField(default=False, verbose_name='پیشنهاد ویزه دارد؟')),
                ('offerPrice', models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت ویژه')),
                ('name_att1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att1', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att10', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att2', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att3', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att4', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att5', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att6', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att7', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att8', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att9', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att_val1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val1', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val10', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val2', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val3', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val4', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val5', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val6', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val7', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val8', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val9', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('product_name_str', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_name_str', to='dataresolve.productnamestr', verbose_name='نام محصول')),
            ],
            options={
                'verbose_name_plural': 'جدول قیمت',
            },
        ),
        migrations.AddField(
            model_name='productnames',
            name='attrs',
            field=models.ManyToManyField(blank=True, related_name='attrss', to='dataresolve.productsattributes', verbose_name='صفات محصول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='full_name',
            field=models.ForeignKey(limit_choices_to={'category_type': 'alter1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_name', to='dataresolve.productcategories', verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='product_main_name',
            field=models.ForeignKey(limit_choices_to={'category_type': 'main'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_name', to='dataresolve.productcategories', verbose_name='نام اصلی محصول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='product_sub_name1',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'alter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_name1', to='dataresolve.productcategories', verbose_name='نام فرعی اول محصول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='sort_by_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sortby_attr', to='dataresolve.productsattributes', verbose_name='صفت جدا کننده\u200cی جدول'),
        ),
        migrations.CreateModel(
            name='MainPageProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products_images_files')),
                ('icon', models.FileField(blank=True, upload_to='products_icon_files', verbose_name='آیکون محصول در منو هدر')),
                ('product_main_name', models.OneToOneField(limit_choices_to={'category_type': 'main'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataresolve.productcategories', verbose_name='نام اصلی محصول')),
            ],
            options={
                'verbose_name_plural': 'اطلاعات عکس محصولات',
            },
        ),
    ]
