# Generated by Django 4.0.6 on 2022-07-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='نام ویژگی')),
                ('category_type', models.CharField(choices=[('main', 'اصلی'), ('alter', 'فرعی')], max_length=10, verbose_name='نوع ویژگی')),
            ],
            options={
                'verbose_name_plural': 'تمام انواع دسته\u200cبندی محصولات',
            },
        ),
    ]
