# Generated by Django 4.0.6 on 2022-07-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='category_type',
            field=models.CharField(choices=[('main', 'اصلی'), ('alter', 'فرعی')], default='اصلی', max_length=10, verbose_name='نوع ویژگی'),
        ),
        migrations.CreateModel(
            name='ProductNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_sub_name2', models.ManyToManyField(blank=True, related_name='sub_name2', to='dataresolve.productcategories', verbose_name='نام فرعی دوم محصول')),
                ('product_main_name', models.ManyToManyField(related_name='main_name', to='dataresolve.productcategories', verbose_name='نام اصلی محصول')),
                ('product_sub_name1', models.ManyToManyField(blank=True, related_name='sub_name1', to='dataresolve.productcategories', verbose_name='نام فرعی اول محصول')),
            ],
            options={
                'verbose_name_plural': 'تمام محصولات',
            },
        ),
    ]
