# Generated by Django 4.0.6 on 2022-08-01 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnames',
            name='att10_order',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت در جدول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att1_order',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت در جدول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att2_order',
            field=models.IntegerField(blank=True, default=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت در جدول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att3_order',
            field=models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت در جدول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att4_order',
            field=models.IntegerField(blank=True, default=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت در جدول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att5_order',
            field=models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت در جدول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att6_order',
            field=models.IntegerField(blank=True, default=6, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت در جدول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att7_order',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت در جدول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att8_order',
            field=models.IntegerField(blank=True, default=8, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت در جدول'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att9_order',
            field=models.IntegerField(blank=True, default=9, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت در جدول'),
        ),
    ]
