# Generated by Django 4.0.6 on 2022-07-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0002_alter_productcategories_category_type_productnames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productnames',
            name='category_sub_name2',
        ),
        migrations.RemoveField(
            model_name='productnames',
            name='product_sub_name1',
        ),
        migrations.RemoveField(
            model_name='productnames',
            name='product_main_name',
        ),
        migrations.AddField(
            model_name='productnames',
            name='product_main_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_name', to='dataresolve.productcategories', verbose_name='نام اصلی محصول'),
        ),
    ]
