# Generated by Django 4.0.6 on 2022-07-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0003_remove_productnames_category_sub_name2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnames',
            name='product_sub_name1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_name1', to='dataresolve.productcategories', verbose_name='نام فرعی اول محصول'),
        ),
    ]
