# Generated by Django 4.0.6 on 2022-07-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0004_productnames_product_sub_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnames',
            name='product_sub_name2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_name2', to='dataresolve.productcategories', verbose_name='نام فرعی دوم محصول'),
        ),
    ]
