# Generated by Django 4.0.6 on 2022-08-04 07:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0004_alter_mainpageproductdata_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageproductdata',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=False, quality=100, scale=None, size=[240, None], upload_to='products_images_files'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='product_image_offer',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=False, null=True, quality=100, scale=None, size=[160, None], upload_to='offer_product_pic', verbose_name='عکس پشنهاد ویژه محصول'),
        ),
    ]
