# Generated by Django 4.0.6 on 2022-07-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0005_productnames_product_sub_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnames',
            name='product_main_name',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'main'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_name', to='dataresolve.productcategories', verbose_name='نام اصلی محصول'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='product_sub_name1',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'alter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_name1', to='dataresolve.productcategories', verbose_name='نام فرعی اول محصول'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='product_sub_name2',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'alter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_name2', to='dataresolve.productcategories', verbose_name='نام فرعی دوم محصول'),
        ),
    ]
