# Generated by Django 4.0.6 on 2022-07-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0006_alter_productnames_product_main_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='category_type',
            field=models.CharField(choices=[('main', 'اصلی'), ('alter', 'فرعی اول'), ('alter1', 'فرعی دوم')], default='اصلی', max_length=10, verbose_name='نوع ویژگی'),
        ),
    ]
