# Generated by Django 4.0.6 on 2022-07-15 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0007_alter_productcategories_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnames',
            name='product_sub_name2',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'alter1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_name2', to='dataresolve.productcategories', verbose_name='نام فرعی دوم محصول'),
        ),
    ]
