# Generated by Django 4.0.6 on 2022-07-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0009_mainpageproductdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=300, unique=True, verbose_name='نام صفت')),
            ],
            options={
                'verbose_name_plural': 'صفات محصولات',
            },
        ),
        migrations.AddField(
            model_name='productnames',
            name='attrs',
            field=models.ManyToManyField(blank=True, related_name='attrs', to='dataresolve.productsattributes', verbose_name='صفات محصول'),
        ),
    ]
