# Generated by Django 4.0.6 on 2022-07-27 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0010_productsattributes_productnames_attrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.ForeignKey(blank=True, limit_choices_to={'category_type': 'main'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='dataresolve.productcategories', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='PossibleProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_value', models.CharField(blank=True, max_length=200, verbose_name='مقدار صفت')),
                ('prod_attr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_attr', to='dataresolve.productsattributes', verbose_name='صفت محصول')),
                ('prod_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_name', to='dataresolve.productnames', verbose_name='نام محصول')),
            ],
        ),
    ]
