# Generated by Django 4.0.6 on 2022-07-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0011_productspricetable_possibleproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsPriceTable',
        ),
    ]
