# Generated by Django 4.0.6 on 2022-07-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0012_delete_productspricetable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PossibleProducts',
            new_name='PossibleProductsAttributes',
        ),
    ]
