# Generated by Django 4.0.6 on 2022-07-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0013_rename_possibleproducts_possibleproductsattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnames',
            name='att1_val',
            field=models.ManyToManyField(blank=True, related_name='att1_val', to='dataresolve.possibleproductsattributes', verbose_name='مقدار'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att2_val',
            field=models.ManyToManyField(blank=True, related_name='att2_val', to='dataresolve.possibleproductsattributes', verbose_name='مقدار'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att3_val',
            field=models.ManyToManyField(blank=True, related_name='att3_val', to='dataresolve.possibleproductsattributes', verbose_name='مقدار'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att4_val',
            field=models.ManyToManyField(blank=True, related_name='att4_val', to='dataresolve.possibleproductsattributes', verbose_name='مقدار'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att5_val',
            field=models.ManyToManyField(blank=True, related_name='att5_val', to='dataresolve.possibleproductsattributes', verbose_name='مقدار'),
        ),
    ]
