# Generated by Django 4.0.6 on 2022-07-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0014_productnames_att1_val_productnames_att2_val_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possibleproductsattributes',
            name='prod_attr',
        ),
        migrations.RemoveField(
            model_name='possibleproductsattributes',
            name='prod_name',
        ),
        migrations.AlterField(
            model_name='possibleproductsattributes',
            name='prod_value',
            field=models.CharField(max_length=200, unique=True, verbose_name='مقدار صفت'),
        ),
    ]
