# Generated by Django 4.0.6 on 2022-07-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0015_remove_possibleproductsattributes_prod_attr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possibleproductsattributes',
            options={'verbose_name_plural': 'صفات کلی محصولات'},
        ),
        migrations.AddField(
            model_name='productnames',
            name='att10_val',
            field=models.ManyToManyField(blank=True, related_name='att10_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att6_val',
            field=models.ManyToManyField(blank=True, related_name='att6_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att7_val',
            field=models.ManyToManyField(blank=True, related_name='att7_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att8_val',
            field=models.ManyToManyField(blank=True, related_name='att8_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن'),
        ),
        migrations.AddField(
            model_name='productnames',
            name='att9_val',
            field=models.ManyToManyField(blank=True, related_name='att9_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='att1_val',
            field=models.ManyToManyField(blank=True, related_name='att1_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='att2_val',
            field=models.ManyToManyField(blank=True, related_name='att2_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='att3_val',
            field=models.ManyToManyField(blank=True, related_name='att3_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='att4_val',
            field=models.ManyToManyField(blank=True, related_name='att4_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='att5_val',
            field=models.ManyToManyField(blank=True, related_name='att5_val', to='dataresolve.possibleproductsattributes', verbose_name='مقادیر ممکن'),
        ),
    ]
