# Generated by Django 4.0.6 on 2022-07-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0016_alter_possibleproductsattributes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possibleproductsattributes',
            options={'ordering': ('prod_value',), 'verbose_name_plural': 'صفات کلی محصولات'},
        ),
    ]
