# Generated by Django 4.0.6 on 2022-07-28 13:52

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0018_alter_productnames_attrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnames',
            name='attrs',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='attrs', sort_value_field_name='attr_name', to='dataresolve.productsattributes', verbose_name='صفات محصول'),
        ),
    ]
