# Generated by Django 4.0.6 on 2022-07-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0019_alter_productnames_attrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnames',
            name='attrs',
            field=models.ManyToManyField(blank=True, related_name='attrs', to='dataresolve.productsattributes', verbose_name='صفات محصول'),
        ),
    ]
