# Generated by Django 4.0.6 on 2022-07-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0020_alter_productnames_attrs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possibleproductsattributes',
            options={'verbose_name_plural': 'صفات کلی محصولات'},
        ),
    ]
