# Generated by Django 4.0.6 on 2022-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0021_alter_possibleproductsattributes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnames',
            name='attrs',
            field=models.ManyToManyField(blank=True, related_name='attrss', to='dataresolve.productsattributes', verbose_name='صفات محصول'),
        ),
    ]
