# Generated by Django 4.0.6 on 2022-07-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0022_alter_productnames_attrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productnames',
            name='attrs',
        ),
    ]
