# Generated by Django 4.0.6 on 2022-07-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0023_remove_productnames_attrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsattributes',
            name='id',
        ),
        migrations.AlterField(
            model_name='productsattributes',
            name='attr_name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, unique=True, verbose_name='نام صفت'),
        ),
    ]
