# Generated by Django 4.0.6 on 2022-07-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0024_remove_productsattributes_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnames',
            name='attrs',
            field=models.ManyToManyField(blank=True, related_name='attrss', to='dataresolve.productsattributes', verbose_name='صفات محصول'),
        ),
    ]
