# Generated by Django 4.0.6 on 2022-07-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0025_productnames_attrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productnames',
            name='att10_val',
        ),
        migrations.RemoveField(
            model_name='productnames',
            name='att1_val',
        ),
        migrations.RemoveField(
            model_name='productnames',
            name='att2_val',
        ),
        migrations.RemoveField(
            model_name='productnames',
            name='att3_val',
        ),
        migrations.RemoveField(
            model_name='productnames',
            name='att4_val',
        ),
        migrations.RemoveField(
            model_name='productnames',
            name='att5_val',
        ),
        migrations.RemoveField(
            model_name='productnames',
            name='att6_val',
        ),
        migrations.RemoveField(
            model_name='productnames',
            name='att7_val',
        ),
        migrations.RemoveField(
            model_name='productnames',
            name='att8_val',
        ),
        migrations.RemoveField(
            model_name='productnames',
            name='att9_val',
        ),
    ]
