# Generated by Django 4.0.6 on 2022-07-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0026_remove_productnames_att10_val_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possibleproductsattributes',
            name='id',
        ),
        migrations.AlterField(
            model_name='possibleproductsattributes',
            name='prod_value',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='مقدار صفت'),
        ),
    ]
