# Generated by Django 4.0.6 on 2022-07-30 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0029_productnamescleaned'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_attr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clean_attr_pn1', to='dataresolve.productsattributes', verbose_name='صفت محصول')),
                ('product_attr_val', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clean_attr_pn1', to='dataresolve.productnamescleaned', verbose_name='مقدار صفت محصول')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clean_name_pn1', to='dataresolve.productnames', verbose_name='نام محصول')),
            ],
        ),
    ]
