# Generated by Django 4.0.6 on 2022-07-30 14:57

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0031_remove_testtable_product_attr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNamesCleaned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_attr_val', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clean_attr_pn', to='dataresolve.possibleproductsattributes', verbose_name='مقدار صفت محصول')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clean_name_pn', to='dataresolve.productnames', verbose_name='نام محصول')),
            ],
        ),
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_attr_val', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='product_name', chained_model_field='product_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clean_attr_pn1', to='dataresolve.productnamescleaned', verbose_name='مقدار صفت محصول')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clean_name_pn1', to='dataresolve.productnames', verbose_name='نام محصول')),
            ],
        ),
    ]
