# Generated by Django 4.0.6 on 2022-07-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0032_productnamescleaned_testtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtable',
            name='product_attr_val',
        ),
        migrations.RemoveField(
            model_name='testtable',
            name='product_name',
        ),
        migrations.DeleteModel(
            name='ProductNamesCleaned',
        ),
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
