# Generated by Django 4.0.6 on 2022-07-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0033_remove_testtable_product_attr_val_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNameAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_attr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_name_attr_attr', to='dataresolve.productsattributes', verbose_name='صفت محصول')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_name_attr_name', to='dataresolve.productnames', verbose_name='نام محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductNameStr',
            fields=[
                ('name', models.CharField(max_length=1500, primary_key=True, serialize=False)),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_name_str_name', to='dataresolve.productnames', verbose_name='نام محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductNameAttrVal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_attr_val', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_name_attr_val_val', to='dataresolve.possibleproductsattributes', verbose_name='مقدار صفت محصول')),
                ('product_name_attr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_n_a', to='dataresolve.productnameattr', verbose_name='نام محصول')),
            ],
        ),
    ]
