# Generated by Django 4.0.6 on 2022-07-30 18:42

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0034_productnameattr_productnamestr_productnameattrval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_att1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att1', to='dataresolve.productnameattr', verbose_name='صفت')),
                ('name_att10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att10', to='dataresolve.productnameattr', verbose_name='صفت')),
                ('name_att2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att2', to='dataresolve.productnameattr', verbose_name='صفت')),
                ('name_att3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att3', to='dataresolve.productnameattr', verbose_name='صفت')),
                ('name_att4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att4', to='dataresolve.productnameattr', verbose_name='صفت')),
                ('name_att5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att5', to='dataresolve.productnameattr', verbose_name='صفت')),
                ('name_att6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att6', to='dataresolve.productnameattr', verbose_name='صفت')),
                ('name_att7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att7', to='dataresolve.productnameattr', verbose_name='صفت')),
                ('name_att8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att8', to='dataresolve.productnameattr', verbose_name='صفت')),
                ('name_att9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att9', to='dataresolve.productnameattr', verbose_name='صفت')),
                ('name_att_val1', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='name_att1', chained_model_field='product_name_attr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val1', to='dataresolve.productnameattrval', verbose_name='مقدار')),
                ('name_att_val10', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='name_att10', chained_model_field='product_name_attr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val10', to='dataresolve.productnameattrval', verbose_name='مقدار')),
                ('name_att_val2', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='name_att2', chained_model_field='product_name_attr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val2', to='dataresolve.productnameattrval', verbose_name='مقدار')),
                ('name_att_val3', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='name_att3', chained_model_field='product_name_attr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val3', to='dataresolve.productnameattrval', verbose_name='مقدار')),
                ('name_att_val4', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='name_att4', chained_model_field='product_name_attr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val4', to='dataresolve.productnameattrval', verbose_name='مقدار')),
                ('name_att_val5', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='name_att5', chained_model_field='product_name_attr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val5', to='dataresolve.productnameattrval', verbose_name='مقدار')),
                ('name_att_val6', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='name_att6', chained_model_field='product_name_attr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val6', to='dataresolve.productnameattrval', verbose_name='مقدار')),
                ('name_att_val7', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='name_att7', chained_model_field='product_name_attr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val7', to='dataresolve.productnameattrval', verbose_name='مقدار')),
                ('name_att_val8', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='name_att8', chained_model_field='product_name_attr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val8', to='dataresolve.productnameattrval', verbose_name='مقدار')),
                ('name_att_val9', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='name_att9', chained_model_field='product_name_attr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val9', to='dataresolve.productnameattrval', verbose_name='مقدار')),
                ('product_name_str', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_name_str', to='dataresolve.productnamestr', verbose_name='نام محصول')),
            ],
            options={
                'verbose_name_plural': 'جدول قیمت',
            },
        ),
    ]
