# Generated by Django 4.0.6 on 2022-07-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0035_productspricetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnamestr',
            name='name',
            field=models.CharField(max_length=5000, primary_key=True, serialize=False),
        ),
    ]
