# Generated by Django 4.0.6 on 2022-07-30 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0036_alter_productnamestr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspricetable',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
        ),
    ]
