# Generated by Django 4.0.6 on 2022-07-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0038_alter_productspricetable_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspricetable',
            name='date_price_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
