# Generated by Django 4.0.6 on 2022-07-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0043_productnamestr_alter_mainpageproductdata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att1',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att10',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att2',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att3',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att4',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att5',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att6',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att7',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att8',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att9',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att_val1',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att_val10',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att_val2',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att_val3',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att_val4',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att_val5',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att_val6',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att_val7',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att_val8',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='name_att_val9',
        ),
        migrations.RemoveField(
            model_name='productspricetable',
            name='product_name_str',
        ),
        migrations.DeleteModel(
            name='ProductNameStr',
        ),
        migrations.DeleteModel(
            name='ProductsPriceTable',
        ),
    ]
