# Generated by Django 4.0.6 on 2022-07-31 10:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0044_remove_productspricetable_name_att1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNameStr',
            fields=[
                ('name', models.CharField(max_length=5000, primary_key=True, serialize=False)),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_name_str_name', to='dataresolve.productnames', verbose_name='نام محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsPriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت')),
                ('date_price_modified', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر قیمت')),
                ('name_att1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att1', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att10', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att2', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att3', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att4', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att5', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att6', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att7', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att8', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att9', to='dataresolve.productsattributes', verbose_name='صفت')),
                ('name_att_val1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val1', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val10', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val2', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val3', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val4', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val5', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val6', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val7', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val8', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('name_att_val9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_att_val9', to='dataresolve.possibleproductsattributes', verbose_name='مقدار')),
                ('product_name_str', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_name_str', to='dataresolve.productnamestr', verbose_name='نام محصول')),
            ],
            options={
                'verbose_name_plural': 'جدول قیمت',
            },
        ),
    ]
