# Generated by Django 4.0.6 on 2022-07-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0045_productnamestr_productspricetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspricetable',
            name='date_price_modified',
            field=models.DateTimeField(verbose_name='آخرین تغییر قیمت'),
        ),
    ]
