# Generated by Django 4.0.6 on 2022-07-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0046_alter_productspricetable_date_price_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspricetable',
            name='date_price_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر قیمت'),
        ),
    ]
