# Generated by Django 4.0.6 on 2022-07-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0049_productspricetable_last_day_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspricetable',
            name='last_day_price',
            field=models.FloatField(null=True, verbose_name='قیمت روز قبل'),
        ),
    ]
