# Generated by Django 4.0.6 on 2022-07-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0050_alter_productspricetable_last_day_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspricetable',
            name='last_price_date',
            field=models.DateTimeField(null=True, verbose_name='آخرین قیمت پیشین'),
        ),
    ]
