# Generated by Django 4.0.6 on 2022-07-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0051_productspricetable_last_price_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspricetable',
            name='date_last_price_modified',
            field=models.DateTimeField(null=True, verbose_name='یکی قبل آخرین تغییر قیمت'),
        ),
    ]
