# Generated by Django 4.0.6 on 2022-07-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0052_productspricetable_date_last_price_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspricetable',
            name='last_price',
            field=models.FloatField(null=True, verbose_name='قیمت'),
        ),
    ]
