# Generated by Django 4.0.6 on 2022-07-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0053_productspricetable_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspricetable',
            name='hasOffer',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد ویزه دارد؟'),
        ),
    ]
