# Generated by Django 4.0.6 on 2022-07-31 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0054_productspricetable_hasoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspricetable',
            name='offerPrice',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت ویژه'),
        ),
    ]
