# Generated by Django 4.0.6 on 2022-07-31 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0055_productspricetable_offerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnames',
            name='sort_by_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sortby_attr', to='dataresolve.productsattributes', verbose_name='مرتب سازی محصول'),
        ),
    ]
