# Generated by Django 4.0.6 on 2022-07-31 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0056_productnames_sort_by_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnames',
            name='product_image_offer',
            field=models.ImageField(null=True, upload_to='offer_product_pic', verbose_name='عکس پشنهاد ویژه محصول'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='category_type',
            field=models.CharField(choices=[('main', 'اصلی'), ('alter', 'فرعی اول'), ('alter1', 'نام نمایش محصول')], default='اصلی', max_length=10, verbose_name='نوع ویژگی'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='product_sub_name2',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'alter1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_name', to='dataresolve.productcategories', verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='sort_by_attr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sortby_attr', to='dataresolve.productsattributes', verbose_name='مرتب سازی محصول'),
        ),
    ]
