# Generated by Django 4.0.6 on 2022-07-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0057_productnames_product_image_offer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productnames',
            old_name='product_sub_name2',
            new_name='full_name',
        ),
    ]
