# Generated by Django 4.0.6 on 2022-07-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0058_rename_product_sub_name2_productnames_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageproductdata',
            name='icon',
            field=models.FileField(blank=True, upload_to='products_icon_files', verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='mainpageproductdata',
            name='file',
            field=models.ImageField(blank=True, upload_to='products_images_files', verbose_name='تصویر'),
        ),
    ]
