# Generated by Django 4.0.6 on 2022-07-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0059_mainpageproductdata_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageproductdata',
            name='file',
        ),
        migrations.AddField(
            model_name='mainpageproductdata',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images_files'),
        ),
        migrations.AlterField(
            model_name='mainpageproductdata',
            name='icon',
            field=models.FileField(blank=True, upload_to='products_icon_files', verbose_name='آیکون محصول در منو هدر'),
        ),
    ]
