# Generated by Django 4.0.6 on 2022-07-31 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0060_remove_mainpageproductdata_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspricetable',
            name='offerPrice',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت ویژه'),
        ),
    ]
