# Generated by Django 4.0.6 on 2022-07-31 20:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0061_alter_productspricetable_offerprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageproductdata',
            name='product_main_name',
            field=models.OneToOneField(limit_choices_to={'category_type': 'main'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataresolve.productcategories', verbose_name='نام اصلی محصول'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='full_name',
            field=models.ForeignKey(limit_choices_to={'category_type': 'alter1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_name', to='dataresolve.productcategories', verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='product_main_name',
            field=models.ForeignKey(limit_choices_to={'category_type': 'main'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_name', to='dataresolve.productcategories', verbose_name='نام اصلی محصول'),
        ),
        migrations.AlterField(
            model_name='productnames',
            name='sort_by_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sortby_attr', to='dataresolve.productsattributes', verbose_name='صفت جدا کننده\u200cی جدول'),
        ),
        migrations.AlterField(
            model_name='productspricetable',
            name='offerPrice',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت ویژه'),
        ),
        migrations.AlterField(
            model_name='productspricetable',
            name='product_name_str',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_name_str', to='dataresolve.productnamestr', verbose_name='نام محصول'),
        ),
    ]
