# Generated by Django 4.0.6 on 2022-08-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPagesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_key', models.CharField(blank=True, max_length=1000, verbose_name='کلید فارسی')),
                ('key', models.CharField(default='default key', max_length=1000, verbose_name='کلید')),
                ('value', models.TextField(blank=True, verbose_name='مقدار')),
                ('file', models.FileField(blank=True, upload_to='general_files', verbose_name='فایل')),
                ('file_compress', models.CharField(blank=True, choices=[('BIG', 'بزرگ'), ('SMALL', 'کوچک')], max_length=10, verbose_name='میزان فشرده\u200cسازی فایل')),
            ],
            options={
                'verbose_name_plural': 'اطلاعات کلی صفحات',
            },
        ),
        migrations.CreateModel(
            name='MainPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_key', models.CharField(blank=True, max_length=1000, verbose_name='کلید فارسی')),
                ('key', models.CharField(default='default key', max_length=1000, verbose_name='کلید')),
                ('value', models.TextField(blank=True, verbose_name='مقدار')),
                ('file', models.FileField(blank=True, upload_to='general_files', verbose_name='فایل')),
                ('file_compress', models.CharField(blank=True, choices=[('BIG', 'بزرگ'), ('SMALL', 'کوچک')], max_length=10, verbose_name='میزان فشرده\u200cسازی فایل')),
            ],
            options={
                'verbose_name_plural': 'اطلاعات صفحه\u200cی اصلی ',
            },
        ),
        migrations.CreateModel(
            name='ProductsPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_key', models.CharField(blank=True, max_length=1000, verbose_name='کلید فارسی')),
                ('key', models.CharField(default='default key', max_length=1000, verbose_name='کلید')),
                ('value', models.TextField(blank=True, verbose_name='مقدار')),
                ('file', models.FileField(blank=True, upload_to='general_files', verbose_name='فایل')),
                ('file_compress', models.CharField(blank=True, choices=[('BIG', 'بزرگ'), ('SMALL', 'کوچک')], max_length=10, verbose_name='میزان فشرده\u200cسازی فایل')),
            ],
            options={
                'verbose_name_plural': 'اطلاعات صفحه\u200cی محصولات',
            },
        ),
    ]
