# Generated by Django 4.0.6 on 2022-07-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPagesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default key', max_length=1000)),
                ('value', models.TextField(blank=True, default='default value')),
                ('file', models.FileField(blank=True, upload_to='general_files')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default key', max_length=1000)),
                ('value', models.TextField(blank=True, default='default value')),
                ('file', models.FileField(blank=True, upload_to='main_page_files')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default key', max_length=1000)),
                ('value', models.TextField(blank=True, default='default value')),
                ('file', models.FileField(blank=True, upload_to='product_page_files')),
            ],
        ),
    ]
