# Generated by Django 4.0.6 on 2022-08-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_data_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagedata',
            name='file',
            field=models.FileField(blank=True, upload_to='main_page_files', verbose_name='فایل'),
        ),
    ]
