# Generated by Django 4.0.6 on 2022-07-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_data_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagedata',
            name='persian_key',
            field=models.CharField(blank=True, default='default key', max_length=1000),
        ),
    ]
