# Generated by Django 4.0.6 on 2022-07-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_data_api', '0002_mainpagedata_persian_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagedata',
            name='persian_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mainpagedata',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
