# Generated by Django 4.0.6 on 2022-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_data_api', '0003_alter_mainpagedata_persian_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpagesdata',
            name='persian_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='productspagedata',
            name='persian_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='generalpagesdata',
            name='value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productspagedata',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
