# Generated by Django 4.0.6 on 2022-07-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_data_api', '0004_generalpagesdata_persian_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalpagesdata',
            options={'verbose_name_plural': 'اطلاعات کلی صفحات'},
        ),
        migrations.AlterModelOptions(
            name='mainpagedata',
            options={'verbose_name_plural': 'اطلاعات صفحه\u200cی اصلی '},
        ),
        migrations.AlterModelOptions(
            name='productspagedata',
            options={'verbose_name_plural': 'اطلاعات صفحه\u200cی محصولات'},
        ),
        migrations.AlterField(
            model_name='generalpagesdata',
            name='file',
            field=models.FileField(blank=True, upload_to='general_files', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='generalpagesdata',
            name='key',
            field=models.CharField(default='default key', max_length=1000, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='generalpagesdata',
            name='persian_key',
            field=models.CharField(blank=True, max_length=1000, verbose_name='کلید فارسی'),
        ),
        migrations.AlterField(
            model_name='generalpagesdata',
            name='value',
            field=models.TextField(blank=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='mainpagedata',
            name='file',
            field=models.FileField(blank=True, upload_to='general_files', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='mainpagedata',
            name='key',
            field=models.CharField(default='default key', max_length=1000, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='mainpagedata',
            name='persian_key',
            field=models.CharField(blank=True, max_length=1000, verbose_name='کلید فارسی'),
        ),
        migrations.AlterField(
            model_name='mainpagedata',
            name='value',
            field=models.TextField(blank=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='productspagedata',
            name='file',
            field=models.FileField(blank=True, upload_to='general_files', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='productspagedata',
            name='key',
            field=models.CharField(default='default key', max_length=1000, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='productspagedata',
            name='persian_key',
            field=models.CharField(blank=True, max_length=1000, verbose_name='کلید فارسی'),
        ),
        migrations.AlterField(
            model_name='productspagedata',
            name='value',
            field=models.TextField(blank=True, verbose_name='مقدار'),
        ),
    ]
