# Generated by Django 4.0.6 on 2022-07-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_data_api', '0005_alter_generalpagesdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpagesdata',
            name='file_compress',
            field=models.CharField(blank=True, max_length=10, verbose_name='میزان فشرده\u200cسازی فایل'),
        ),
        migrations.AddField(
            model_name='mainpagedata',
            name='file_compress',
            field=models.CharField(blank=True, max_length=10, verbose_name='میزان فشرده\u200cسازی فایل'),
        ),
        migrations.AddField(
            model_name='productspagedata',
            name='file_compress',
            field=models.CharField(blank=True, max_length=10, verbose_name='میزان فشرده\u200cسازی فایل'),
        ),
    ]
