# Generated by Django 4.0.6 on 2022-07-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0008_alter_productnames_product_sub_name2'),
        ('pages_data_api', '0006_generalpagesdata_file_compress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpagesdata',
            name='file_compress',
            field=models.CharField(blank=True, choices=[('BIG', 'بزرگ'), ('SMALL', 'کوچک')], max_length=10, verbose_name='میزان فشرده\u200cسازی فایل'),
        ),
        migrations.AlterField(
            model_name='mainpagedata',
            name='file_compress',
            field=models.CharField(blank=True, choices=[('BIG', 'بزرگ'), ('SMALL', 'کوچک')], max_length=10, verbose_name='میزان فشرده\u200cسازی فایل'),
        ),
        migrations.AlterField(
            model_name='productspagedata',
            name='file_compress',
            field=models.CharField(blank=True, choices=[('BIG', 'بزرگ'), ('SMALL', 'کوچک')], max_length=10, verbose_name='میزان فشرده\u200cسازی فایل'),
        ),
        migrations.CreateModel(
            name='MainPageProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to='products_images_files', verbose_name='فایل')),
                ('product_main_name', models.ForeignKey(blank=True, limit_choices_to={'category_type': 'main'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataresolve.productcategories', verbose_name='نام اصلی محصول')),
            ],
            options={
                'verbose_name_plural': 'اطلاعات عکس محصولات',
            },
        ),
    ]
