# Generated by Django 4.0.6 on 2022-07-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataresolve', '0008_alter_productnames_product_sub_name2'),
        ('pages_data_api', '0007_alter_generalpagesdata_file_compress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageproductdata',
            name='product_main_name',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'main'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataresolve.productcategories', unique=True, verbose_name='نام اصلی محصول'),
        ),
    ]
