# Generated by Django 4.0.6 on 2022-07-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_data_api', '0009_alter_mainpageproductdata_product_main_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPageProductData',
        ),
    ]
