# Generated by Django 4.0.6 on 2022-07-31 15:01

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages_data_api', '0010_delete_mainpageproductdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpagesdata',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='general_files', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='mainpagedata',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='general_files', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='productspagedata',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='general_files', verbose_name='فایل'),
        ),
    ]
