# Generated by Django 4.0.6 on 2022-07-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_data_api', '0011_alter_generalpagesdata_file_alter_mainpagedata_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpagesdata',
            name='file',
            field=models.FileField(blank=True, upload_to='general_files', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='mainpagedata',
            name='file',
            field=models.FileField(blank=True, upload_to='general_files', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='productspagedata',
            name='file',
            field=models.FileField(blank=True, upload_to='general_files', verbose_name='فایل'),
        ),
    ]
